language: python
jobs:
   include:
      - name: "Python 3.7 on macOS"
        os: osx
        osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
        language: shell       # 'language: python' is an error on Travis CI macOS
      - name: "Python 3.8.0 on Windows"
        os: windows           # Windows 10.0.17134 N/A Build 17134
        language: shell       # 'language: python' is an error on Travis CI Windows
install:
   - pip install numpy
   - pip install pytest
   - pip install .
script:
   - cd tests
   - pytest
